name: pypsa-earth-fepbe
channels:
  - bioconda
  - gurobi
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _python_abi3_support=1.0
  - adwaita-icon-theme=48.1
  - affine=2.4.0
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.12.15
  - aiosignal=1.4.0
  - alsa-lib=1.2.14
  - ampl-asl=1.0.0
  - amply=0.1.6
  - anyio=4.10.0
  - appdirs=1.4.4
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=25.1.0
  - arrow=1.3.0
  - asttokens=3.0.0
  - async-lru=2.0.5
  - at-spi2-atk=2.38.0
  - at-spi2-core=2.40.3
  - atk-1.0=2.38.0
  - atlite=0.4.1
  - attr=2.5.2
  - attrs=25.3.0
  - aws-c-auth=0.9.0
  - aws-c-cal=0.9.2
  - aws-c-common=0.12.4
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.5
  - aws-c-http=0.10.4
  - aws-c-io=0.21.2
  - aws-c-mqtt=0.13.3
  - aws-c-s3=0.8.6
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.33.1
  - aws-sdk-cpp=1.11.606
  - azure-core-cpp=1.16.0
  - azure-identity-cpp=1.12.0
  - azure-storage-blobs-cpp=12.14.0
  - azure-storage-common-cpp=12.10.0
  - azure-storage-files-datalake-cpp=12.12.0
  - babel=2.17.0
  - beautifulsoup4=4.13.5
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - blis=0.9.0
  - blosc=1.21.6
  - bokeh=3.8.0
  - bottleneck=1.6.0
  - branca=0.8.1
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - brotlicffi=1.1.0.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - c-blosc2=2.21.2
  - ca-certificates=2025.8.3
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.5.2
  - cairo=1.18.4
  - cartopy=0.25.0
  - cdsapi=0.7.6
  - certifi=2025.8.3
  - cffi=1.17.1
  - cfgrib=0.9.15.0
  - cfgv=3.3.1
  - cftime=1.6.4
  - chaospy=4.3.20
  - charset-normalizer=3.4.3
  - click=8.1.8
  - click-plugins=1.1.1.2
  - cligj=0.7.2
  - cloudpickle=3.1.1
  - coin-or-cbc=2.10.12
  - coin-or-cgl=0.60.9
  - coin-or-clp=1.17.10
  - coin-or-osi=0.108.11
  - coin-or-utils=2.11.12
  - coincbc=2.10.12
  - colorama=0.4.6
  - colorcet=3.1.0
  - comm=0.2.3
  - configargparse=1.7.1
  - connection_pool=0.0.3
  - contextily=1.6.2
  - contourpy=1.3.3
  - country_converter=1.3.1
  - cppad=20250000.2
  - cpython=3.11.13
  - cryptography=45.0.7
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - cytoolz=1.0.1
  - dask=2025.9.1
  - dask-core=2025.9.1
  - datashader=0.18.2
  - datrie=0.8.3
  - dbus=1.16.2
  - debugpy=1.8.17
  - decorator=5.2.1
  - defusedxml=0.7.1
  - deprecation=2.1.0
  - distlib=0.4.0
  - distributed=2025.9.1
  - docutils=0.22
  - double-conversion=3.3.1
  - dpath=2.2.0
  - earth-osm=2.3.post1
  - eccodes=2.42.0
  - ecmwf-datastores-client=0.4.0
  - entsoe-py=0.7.4
  - epoxy=1.5.10
  - et_xmlfile=2.0.0
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - fake-useragent=2.2.0
  - filelock=3.19.1
  - findlibs=0.1.2
  - fiona=1.10.1
  - folium=0.20.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.60.0
  - fqdn=1.5.1
  - freeglut=3.2.2
  - freetype=2.14.1
  - freexl=2.0.0
  - fribidi=1.0.16
  - frozenlist=1.7.0
  - fsspec=2025.9.0
  - future=1.0.0
  - gdk-pixbuf=2.44.1
  - geographiclib=2.1
  - geopandas=1.1.1
  - geopandas-base=1.1.1
  - geopy=2.4.1
  - geos=3.14.0
  - geotiff=1.7.4
  - geoviews=1.14.1
  - geoviews-core=1.14.1
  - gflags=2.2.2
  - giflib=5.2.2
  - gitdb=4.0.12
  - gitpython=3.1.45
  - glib-tools=2.86.0
  - glog=0.7.1
  - glpk=5.0
  - gmp=6.3.0
  - google-api-core=2.25.1
  - google-auth=2.40.3
  - google-cloud-core=2.4.3
  - google-cloud-storage=3.4.0
  - google-crc32c=1.7.1
  - google-resumable-media=2.7.2
  - googleapis-common-protos=1.70.0
  - graphite2=1.3.14
  - graphviz=13.1.2
  - grpcio=1.73.1
  - gtk3=3.24.43
  - gts=0.7.6
  - gurobi=12.0.3
  - h11=0.16.0
  - h2=4.3.0
  - h5netcdf=1.6.4
  - h5py=3.14.0
  - harfbuzz=11.5.0
  - hdf4=4.2.15
  - hdf5=1.14.6
  - hicolor-icon-theme=0.17
  - highspy=1.11.0
  - holoviews=1.21.0
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - humanfriendly=10.0
  - hvplot=0.12.1
  - hyperframe=6.1.0
  - icu=75.1
  - identify=2.6.14
  - idna=3.10
  - importlib-metadata=8.7.0
  - importlib_metadata=8.7.0
  - inflate64=1.0.3
  - iniconfig=2.0.0
  - ipopt=3.14.19
  - ipykernel=6.30.1
  - ipython=9.5.0
  - ipython_pygments_lexers=1.1.1
  - isoduration=20.11.0
  - jasper=4.2.8
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.2
  - json-c=0.18
  - json5=0.12.1
  - jsonpointer=3.0.0
  - jsonschema=4.25.1
  - jsonschema-specifications=2025.9.1
  - jsonschema-with-format-nongpl=4.25.1
  - jupyter-lsp=2.3.0
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - jupyter_events=0.12.0
  - jupyter_server=2.17.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.4.7
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - keyutils=1.6.3
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lark=1.2.2
  - lcms2=2.17
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libabseil=20250512.1
  - libaec=1.1.4
  - libarchive=3.8.1
  - libarrow=21.0.0
  - libarrow-acero=21.0.0
  - libarrow-compute=21.0.0
  - libarrow-dataset=21.0.0
  - libarrow-substrait=21.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang-cpp21.1=21.1.0
  - libclang13=21.1.0
  - libcrc32c=1.1.2
  - libcups=2.3.3
  - libcurl=8.14.1
  - libdeflate=1.24
  - libdrm=2.4.125
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.1
  - libffi=3.4.6
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgd=2.3.3
  - libgdal-core=3.10.3
  - libgdal-hdf4=3.10.3
  - libgdal-hdf5=3.10.3
  - libgdal-netcdf=3.10.3
  - libgfortran=15.1.0
  - libgfortran5=15.1.0
  - libgl=1.7.0
  - libglib=2.86.0
  - libglu=9.0.3
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.1.0
  - libgoogle-cloud=2.39.0
  - libgoogle-cloud-storage=2.39.0
  - libgrpc=1.73.1
  - libhwloc=2.12.1
  - libiconv=1.18
  - libjpeg-turbo=3.1.0
  - libkml=1.3.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm21=21.1.0
  - liblzma=5.8.1
  - libnetcdf=4.9.3
  - libnghttp2=1.67.0
  - libnsl=2.0.1
  - libntlm=1.8
  - libopengl=1.7.0
  - libopentelemetry-cpp=1.21.0
  - libopentelemetry-cpp-headers=1.21.0
  - libparquet=21.0.0
  - libpciaccess=0.18
  - libpng=1.6.50
  - libpq=17.6
  - libprotobuf=6.31.1
  - libre2-11=2025.08.12
  - librsvg=2.58.4
  - librttopo=1.1.0
  - libscotch=7.0.8
  - libsodium=1.0.20
  - libspatialite=5.1.0
  - libspral=2025.05.20
  - libsqlite=3.50.4
  - libssh2=1.11.1
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libthrift=0.22.0
  - libtiff=4.7.0
  - libutf8proc=2.11.0
  - libuuid=2.41.1
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.11.0
  - libxml2=2.13.8
  - libxslt=1.1.43
  - libzip=1.11.2
  - libzlib=1.3.1
  - linkify-it-py=2.0.3
  - linopy=0.5.7
  - llvmlite=0.44.0
  - locket=1.0.0
  - lxml=6.0.1
  - lz4=4.4.4
  - lz4-c=1.10.0
  - lzo=2.10
  - mapclassify=2.10.0
  - markdown=3.9
  - markdown-it-py=4.0.0
  - markupsafe=3.0.2
  - matplotlib=3.10.6
  - matplotlib-base=3.10.6
  - matplotlib-inline=0.1.7
  - mdit-py-plugins=0.5.0
  - mdurl=0.1.2
  - memory_profiler=0.61.0
  - mercantile=1.2.1
  - metis=5.1.0
  - minizip=4.0.10
  - mistune=3.1.4
  - mpfr=4.2.1
  - msgpack-python=1.1.1
  - multidict=6.6.3
  - multipledispatch=0.6.0
  - multiurl=0.3.7
  - multivolumefile=0.2.3
  - mumps-include=5.8.1
  - mumps-seq=5.8.1
  - munkres=1.1.4
  - narwhals=2.5.0
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - netcdf4=1.7.2
  - networkx=3.5
  - nlohmann_json=3.12.0
  - nodeenv=1.9.1
  - nomkl=1.0
  - notebook-shim=0.2.4
  - numba=0.61.2
  - numexpr=2.12.1
  - numpoly=1.2.14
  - numpy=1.26.4
  - openjpeg=2.5.3
  - openldap=2.6.10
  - openpyxl=3.1.5
  - openssl=3.5.3
  - orc=2.2.0
  - overrides=7.7.0
  - packaging=25.0
  - pandas=2.3.2
  - pandocfilters=1.5.0
  - panel=1.8.1
  - pango=1.56.4
  - param=2.2.1
  - parso=0.8.5
  - partd=1.4.2
  - patsy=1.0.1
  - pcre2=10.46
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.3.0
  - pip=25.2
  - pixman=0.46.4
  - plac=1.4.5
  - platformdirs=4.4.0
  - pluggy=1.6.0
  - ply=3.11
  - polars=1.33.1
  - polars-default=1.33.1
  - powerplantmatching=0.7.1
  - pre-commit=4.3.0
  - progressbar2=4.5.0
  - proj=9.6.2
  - prometheus-cpp=1.3.0
  - prometheus_client=0.22.1
  - prompt-toolkit=3.0.52
  - propcache=0.3.1
  - proto-plus=1.26.1
  - protobuf=6.31.1
  - psutil=7.1.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pulp=2.7.0
  - pure_eval=0.2.3
  - py-cpuinfo=9.0.0
  - py7zr=1.0.0
  - pyarrow=21.0.0
  - pyarrow-core=21.0.0
  - pyasn1=0.6.1
  - pyasn1-modules=0.4.2
  - pybcj=1.0.6
  - pycountry=24.6.1
  - pycparser=2.22
  - pycryptodomex=3.23.0
  - pyct=0.5.0
  - pydoe2=1.3.0
  - pygments=2.19.2
  - pyogrio=0.11.0
  - pyomo=6.9.4
  - pyopenssl=25.1.0
  - pyparsing=3.2.4
  - pyppmd=1.1.0
  - pyproj=3.7.2
  - pypsa=0.30.3
  - pyscipopt=5.6.0
  - pyshp=3.0.1
  - pyside6=6.9.2
  - pysocks=1.7.1
  - pytables=3.10.2
  - pytest=8.4.2
  - python=3.11.13
  - python-dateutil=2.9.0.post0
  - python-eccodes=2.37.0
  - python-fastjsonschema=2.21.2
  - python-gil=3.11.13
  - python-json-logger=2.0.7
  - python-tzdata=2025.2
  - python-utils=3.9.1
  - python_abi=3.11
  - pytz=2025.2
  - pyu2f=0.1.5
  - pyviz_comms=3.0.6
  - pyyaml=6.0.2
  - pyzmq=27.1.0
  - pyzstd=0.17.0
  - qhull=2020.2
  - qt6-main=6.9.2
  - rasterio=1.4.3
  - re2=2025.08.12
  - readline=8.2
  - referencing=0.36.2
  - requests=2.32.5
  - reretry=0.11.8
  - reverse-geocode=1.4.1
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rfc3987-syntax=1.1.0
  - rich=14.1.0
  - rioxarray=0.19.0
  - rpds-py=0.27.1
  - rsa=4.9.1
  - ruamel.yaml=0.17.26
  - ruamel.yaml.clib=0.2.12
  - s2n=1.5.23
  - scikit-learn=1.7.2
  - scip=9.2.3
  - scipy=1.15.2
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - send2trash=1.8.3
  - setuptools=80.9.0
  - shapely=2.1.1
  - six=1.17.0
  - smart_open=7.3.1
  - smmap=5.0.2
  - snakemake-minimal=7.32.4
  - snappy=1.2.2
  - sniffio=1.3.1
  - snuggs=1.4.7
  - sortedcontainers=2.4.0
  - soupsieve=2.8
  - sqlite=3.50.4
  - stack_data=0.6.3
  - statsmodels=0.14.5
  - stopit=1.1.2
  - tabulate=0.9.0
  - tbb=2022.2.0
  - tblib=3.1.0
  - terminado=0.18.1
  - texttable=1.7.0
  - threadpoolctl=3.6.0
  - throttler=1.2.2
  - tinycss2=1.4.0
  - tk=8.6.13
  - tomli=2.2.1
  - toolz=1.0.0
  - toposort=1.10
  - tornado=6.5.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - tsam=2.3.9
  - types-python-dateutil=2.9.0.20250822
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - typing_utils=0.1.0
  - tzdata=2025b
  - uc-micro-py=1.0.3
  - ukkonen=1.0.1
  - unicodedata2=16.0.0
  - unidecode=1.3.8
  - uri-template=1.3.0
  - uriparser=0.9.8
  - urllib3=2.5.0
  - validators=0.35.0
  - virtualenv=20.34.0
  - wayland=1.24.0
  - wcwidth=0.2.13
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.45.1
  - wrapt=1.17.3
  - xarray=2025.1.2
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xerces-c=3.2.5
  - xkeyboard-config=2.45
  - xlrd=2.0.2
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxinerama=1.1.5
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - xyzservices=2025.4.0
  - yaml=0.2.5
  - yarl=1.20.1
  - yte=1.8.1
  - zeromq=4.3.5
  - zict=3.0.0
  - zipfile-deflate64=0.2.0
  - zipp=3.23.0
  - zlib=1.3.1
  - zlib-ng=2.2.5
  - zstandard=0.25.0
  - zstd=1.5.7
  - pip:
      - currencyconverter==0.18.9
      - geojson==3.2.0
      - googledrivedownloader==1.1.0
      - searoute==1.4.3
prefix: /home/alex-charly/anaconda3/envs/pypsa-earth-AP10-v2
